# Generated by Django 3.0.5 on 2020-04-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0002_auto_20200416_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to='accounts.Profile'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='unlikes',
        ),
        migrations.AddField(
            model_name='post',
            name='unlikes',
            field=models.ManyToManyField(related_name='unliked_posts', to='accounts.Profile'),
        ),
    ]
