# Generated by Django 3.0.5 on 2020-04-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200416_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='liked_by',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='unlikes',
            new_name='unliked_by',
        ),
    ]
