# Generated by Django 3.0.5 on 2020-04-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200416_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='unliked_by',
            new_name='disliked_by',
        ),
    ]
