# Generated by Django 3.0.5 on 2020-04-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20200416_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='like_time',
            new_name='like_date',
        ),
    ]
