# Generated by Django 3.0.5 on 2020-04-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='activity',
            field=models.TextField(default='some activity.', max_length=200),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='activity_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
