# Generated by Django 3.0.5 on 2020-04-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_activity',
        ),
    ]
